fix for a libboost_system-related link error
maybe a change since whenever i last built this?

g++ -pedantic -std=c++98 -O3 -Wall -Wextra -Werror -Wfatal-errors -I/usr/include  -Wl,-s -Wl,-L /usr/lib -Wl,-rpath /usr/lib -Wl,-L /usr/lib  maildirs.cpp  -lboost_filesystem -o maildirs
/usr/lib/gcc/i586-suse-linux/4.7/../../../../i586-suse-linux/bin/ld: /tmp/ccaJi5rg.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
/usr/lib/gcc/i586-suse-linux/4.7/../../../../i586-suse-linux/bin/ld: note: '_ZN5boost6system15system_categoryEv' is defined in DSO /usr/lib/libboost_system.so.1.49.0 so try adding it to the linker command line
/usr/lib/libboost_system.so.1.49.0: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make: *** [maildirs] Error 1